#!/bin/sh /etc/rc.common
START=97
USE_PROCD=1
PROG=/usr/sbin/rodial-dt

start_service() {
    procd_open_instance
    procd_set_param command $PROG
    procd_set_param respawn
    procd_close_instance
}
stop_service() {
    procd_kill_instance
}
