#!/bin/sh /etc/rc.common
START=96
USE_PROCD=1
PROG=/usr/sbin/rodial-proxy

start_service() {
    procd_open_instance
    procd_set_param command $PROG --config /etc/config/rodial
    procd_set_param respawn
    procd_close_instance
}
stop_service() {
    procd_kill_instance
}